# Numpy

In [1]:
import numpy as np

In [2]:
L1 = [1,2,3,4,5,6,7,8] # crear una lista


In [3]:
x1 = np.array(L1) # creo un array a partir de la lista L1
x1

array([1, 2, 3, 4, 5, 6, 7, 8])

In [4]:
x2 = np.array(L1, dtype='float32') # le indico a numpy que quiero un array de tipo float de 32 bits 
x2

array([1., 2., 3., 4., 5., 6., 7., 8.], dtype=float32)

- bool_
- int_ = int64, intc, intp , int8, int16, int32, int64
- uint8, uint16, uint32, uint64 
- float_ = float64, float16, float32, float64 (+/- 9999999999e9999) # un bit para el signo 10 para la mantisa y 5 para el exponente 
- complex_ = complex64, complex64, complex128 (la mitad de los bits son para la parte real y la otra mitad para la parte imaginaria) $a,b \in \text{ float_}$ 

In [5]:
np.zeros((3,4)) # un array de ceros de 3 filas y 4 columnas 

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [6]:
np.ones((4,3)) # un array de unos de 4 filas y 3 columnas

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [7]:
np.arange(10) # un array de 10 números

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(3,12,dtype=float) # un array desde 3 hasta 12-1 de tipo float

array([ 3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [10]:
np.arange(4,5,0.1) # desde el 4 al 5-4 de 0.1 en 0.1

array([4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9])

In [11]:
np.linspace(1.,7.,12)# 12 numeros desde 1 a 7 

array([1.        , 1.54545455, 2.09090909, 2.63636364, 3.18181818,
       3.72727273, 4.27272727, 4.81818182, 5.36363636, 5.90909091,
       6.45454545, 7.        ])

In [12]:
np.eye(5)# matriz identidad de 5 filas y cinco columnas 

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [15]:
x = np.arange((24))
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [16]:
x.reshape((6,4)) # refiguro la matrix x con 3 filas y 4 columnas , como x era de (8,3) o sea 24 , el reshape 
# debe resultar también 24 como es el caso de 6,4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [17]:
x.reshape((3,8))

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [18]:
x = np.array([[1,2,3,4],[5,6,7,8]])
x

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [19]:
np.ravel(x)# aplanamos el array x 

array([1, 2, 3, 4, 5, 6, 7, 8])

In [20]:
x.flatten() # crea una copia del array x aplanado

array([1, 2, 3, 4, 5, 6, 7, 8])

In [21]:
np.transpose(x)

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [22]:
x

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [24]:
np.resize(x,(5,3)) # redimensiono el array x en 5 filas y 3 columnas 
# si no hay elementos suficientes se repiten los elementos del array hasta completar el nuevo array 

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 1],
       [2, 3, 4],
       [5, 6, 7]])

### Ejercicios
1. crear un array de datos con valores entre 2  y 120
2. crear una matriz 4x4 con los valores desde 0 hasta 15.
3. crear la identidad 7x7 
4. crear un array de 20 elementos y transformarlos en una matrix 5x4
5. crear un array con 20 números con los valores entre 0 y 5 espaciados de forma uniforme

In [31]:
# ejercicio 1
a = np.arange(2,120)
a

array([  2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,  14,
        15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,  27,
        28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,  40,
        41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,  53,
        54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,  66,
        67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,  79,
        80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,  92,
        93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104, 105,
       106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118,
       119])

In [35]:
# ejercicio 2
b = np.arange(0,16)
b.reshape((4,4))


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [36]:
# ejercicio 3
np.eye(7)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [37]:
# ejercicio 4
c = np.arange(20)
c.reshape((5,4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [38]:
np.linspace(0.,5.,20)

array([0.        , 0.26315789, 0.52631579, 0.78947368, 1.05263158,
       1.31578947, 1.57894737, 1.84210526, 2.10526316, 2.36842105,
       2.63157895, 2.89473684, 3.15789474, 3.42105263, 3.68421053,
       3.94736842, 4.21052632, 4.47368421, 4.73684211, 5.        ])

## Propiedad de los arrays

In [41]:
x = np.arange(12)
x=x.reshape((3,4))
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [43]:
# tendremos las dimensiones de filas columnas y profundidad 
# en python el número de dimensiones se llama el rango
x.ndim

2

In [44]:
x.shape # que forma tienen 

(3, 4)

In [45]:
x.size # tamaño o numero de elementos que tiene la matriz

12

In [46]:
x.dtype # tipo de dato de la matriz

dtype('int64')

In [48]:
#x.itemsize # tamaño de cada uno de los elementos de la matriz
print('cada elemento de la matriz ocupa {} bytes'.format(x.itemsize))

cada elemento de la matriz ocupa 8 bytes


In [49]:
x.data # es la posición de memoria donde está la matriz

In [50]:
x[2] # fila nº 2

array([ 8,  9, 10, 11])

In [51]:
x[2,1] # fila 2 y columna 1

9

In [53]:
x.shape = (4,3) # redimensionamos la matriz a 4 filas y 3 columnas 
x

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [54]:
x[1:3,0:2] # de la fila 1 a la 3-1 y de la columna 0 a la 2-1

array([[3, 4],
       [6, 7]])

In [55]:
y = np.arange(12)
y[3:7]

array([3, 4, 5, 6])

In [57]:
y[1:7:2]

array([1, 3, 5])

In [58]:
z = np.arange(10,6,-1) # del 10 al 6 quitando uno cada vez
z

array([10,  9,  8,  7])

In [59]:
# puedo usar este array para acceder a las posiciones del array y
y[z]

array([10,  9,  8,  7])

In [60]:
# podemos acceder a los elementos por condición booleana 
x = np.arange(50)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [61]:
x[x>30]

array([31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47,
       48, 49])

In [62]:
cond = x<25 # condicion boolena 
cond

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False])

In [63]:
x[cond] # muestra los elementos dada la condición boolenana anterior 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [64]:
x[12:24] = 1 # asigno el 1 a los elementos que hay en el rango dado

In [65]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [66]:
x[13:16] = [6,9,12]
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11,  1,  6,  9, 12,  1,
        1,  1,  1,  1,  1,  1,  1, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [67]:
x.dtype

dtype('int64')

In [68]:
x[5]= 3.1415 # asigno un valor float a un elemento de dun array de enteros, lo que me va a dar es la parte entera
x

array([ 0,  1,  2,  3,  4,  3,  6,  7,  8,  9, 10, 11,  1,  6,  9, 12,  1,
        1,  1,  1,  1,  1,  1,  1, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [81]:
a=np.eye(7)
a[0:7:6]=5
a[:,0:7:6]=5
a

array([[5., 5., 5., 5., 5., 5., 5.],
       [5., 1., 0., 0., 0., 0., 5.],
       [5., 0., 1., 0., 0., 0., 5.],
       [5., 0., 0., 1., 0., 0., 5.],
       [5., 0., 0., 0., 1., 0., 5.],
       [5., 0., 0., 0., 0., 1., 5.],
       [5., 5., 5., 5., 5., 5., 5.]])

## copias y vista de arrays

In [82]:
x = np.arange(10)

In [83]:
y = x # aqui lo que hago es apuntantar a ladireccion de memoria donde está x y todo lo que haga en y se refleja en x

In [85]:
y.shape =(2,5)
y

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [86]:
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [88]:
z = x.copy() # aqui hacemos una copia de x , por lo que z no es una referencia a x sino una variable nueva con
# los datos de x 
z

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [89]:
z is x 

False

In [90]:
 y is x

True

In [91]:
# podemos hacer una vista de x , lo que significa que tiene los mismo elementos pero al modificar la vista , no 
# modificamos a x
t = x.view()
t

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [93]:
t.shape=(5,2)
t

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [94]:
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [95]:
s = x[0:2,1:3] # esto también es una vista , ya que el objeto s es distinto del objeto x

In [96]:
s

array([[1, 2],
       [6, 7]])

In [97]:
s[:]=5
s

array([[5, 5],
       [5, 5]])

In [98]:
x

array([[0, 5, 5, 3, 4],
       [5, 5, 5, 8, 9]])

## Funciones universales (ufunc) 
- unarias: sqrt, sin, cos , **2
- binarias: maximum, ninimun

In [2]:
x = np.arange(10)

In [3]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
x+3 # sumo 3 a cada elemento del array x

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [5]:
x/3

array([0.        , 0.33333333, 0.66666667, 1.        , 1.33333333,
       1.66666667, 2.        , 2.33333333, 2.66666667, 3.        ])

In [6]:
alpha = np.linspace(0,2*np.pi,4) # entre cero y 2*pi 4 elementos

In [7]:
alpha

array([0.        , 2.0943951 , 4.1887902 , 6.28318531])

In [8]:
np.sin(alpha)

array([ 0.00000000e+00,  8.66025404e-01, -8.66025404e-01, -2.44929360e-16])

In [9]:
np.cos(alpha)

array([ 1. , -0.5, -0.5,  1. ])

In [11]:
np.tan(alpha)

array([ 0.00000000e+00, -1.73205081e+00,  1.73205081e+00, -2.44929360e-16])

In [12]:
x = np.arange(10)

In [13]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
np.exp(x)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [15]:
np.exp2(x)

array([  1.,   2.,   4.,   8.,  16.,  32.,  64., 128., 256., 512.])

In [16]:
np.power(3,x)

array([    1,     3,     9,    27,    81,   243,   729,  2187,  6561,
       19683])

In [17]:
np.power(x,2)

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [18]:
np.log(x) # el logaritmo de cero es -infinito 

/tmp/ipykernel_3725/1277889159.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(x)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [19]:
np.log2(x)

/tmp/ipykernel_3725/3275510840.py:1: RuntimeWarning: divide by zero encountered in log2
  np.log2(x)


array([      -inf, 0.        , 1.        , 1.5849625 , 2.        ,
       2.32192809, 2.5849625 , 2.80735492, 3.        , 3.169925  ])

In [20]:
np.log10(x)

/tmp/ipykernel_3725/1114196279.py:1: RuntimeWarning: divide by zero encountered in log10
  np.log10(x)


array([      -inf, 0.        , 0.30103   , 0.47712125, 0.60205999,
       0.69897   , 0.77815125, 0.84509804, 0.90308999, 0.95424251])

In [21]:
np.nansum(x)# hace la suma de los elementos del array sin tener en cuenta los na's 

45

$\displaystyle\sum_{i=0}^n x_i$

In [22]:
np.sum(x) # sumatorio

45

$$\prod_{i=1}^n x_i$$

In [23]:
np.prod(x)# productorio

0

In [24]:
np.mean(x)# media

4.5

In [25]:
np.median(x) # mediana

4.5

In [26]:
np.min(x)

0

In [27]:
np.max(x)

9

In [28]:
np.std(x) # desviación standard (standard deviation)

2.8722813232690143

In [29]:
np.var(x) # varianza

8.25

In [30]:
np.argmin(x) # la posición donde se encuentra el valor más pequeño

0

In [31]:
np.argmax(x) # la posición donde se encuentra el valor más grande

9

In [32]:
np.percentile(x, q=0.25) # calcula el percentil del 25% del array x

0.0225

In [33]:
np.any(x) # devuelve True si alguno de los elementos es True

True

In [35]:
np.all(x) # devuelve True si todos los elementos son True (como cero es False ) el resultado es False

False

In [44]:
np.random.seed(2019) # con el paŕametro seed van a salir los mismo números aleatorios 
z = np.random.random((3,5))# 3 filas y 5 columnas de valores aleatorios entre 0 y 1

In [42]:
z

array([[0.90348221, 0.39308051, 0.62396996, 0.6378774 , 0.88049907],
       [0.29917202, 0.70219827, 0.90320616, 0.88138193, 0.4057498 ],
       [0.45244662, 0.26707032, 0.16286487, 0.8892147 , 0.14847623]])

In [45]:
z.sum() # suma todos los valores del array z

8.550690063213514

In [39]:
z.sum(axis=0)# con el parámetro axis=0 suma cada columna

array([1.42181833, 1.49451988, 1.09162363, 1.62149168, 0.95564988])

In [40]:
z.sum(axis=1) # con el parámetro axis=1 suma cada fila 

array([0.66303363, 3.24781762, 2.67425215])

 - axis = 0 columnas
 - axis = 1 filas
 - axis = 2 profundidad

## Ejercicios sobre numpy
aqui puedes ver [ejercicios sobre numpy](https://github.com/rougier/numpy-100/blob/master/100_Numpy_exercises.ipynb)